const USERS = [
  {id:'u-growth-head',name:'Growth Head',email:'growth.head@cake.vn',roles:['Growth Head']},
  {id:'u-finance-manager',name:'Finance Manager',email:'finance.manager@cake.vn',roles:['Finance Approver','Finance Manager']},
  {id:'u-finance-ops',name:'Finance Ops',email:'finance.ops@cake.vn',roles:['Finance Approver']},
  {id:'u-director',name:'Growth Director',email:'growth.director@cake.vn',roles:['Growth Director']},
  {id:'u-ops-lead',name:'Ops Lead',email:'ops.lead@cake.vn',roles:['Ops Approver']},
  {id:'u-product',name:'Tuấn Phạm',email:'tuan.pham@cake.vn',roles:['Tech Product Manager','Payout Admin']},
];
const ROLES=['Growth Head','Finance Approver','Finance Manager','Growth Director','Ops Approver'];
const CAMPAIGNS=[
  {id:'TD_REFERRAL_2026',name:'TD Referral 2026',fixedAmount:100000,budgetRemaining:420000000,dailyCap:200000000},
  {id:'GROWTH_CASHBACK_Q3',name:'Growth Cashback Q3',fixedAmount:null,budgetRemaining:760000000,dailyCap:300000000},
];
const clone=v=>JSON.parse(JSON.stringify(v));
const now=()=>new Date().toISOString();
const money=v=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(v||0));
const dt=v=>v?new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(v)):'—';
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<span class="v2-icon">${({search:'⌕',upload:'⇧',eye:'◉',back:'←',check:'✓',x:'×',download:'⇩',refresh:'↻',retry:'↺',plus:'+',pencil:'✎',warning:'!',settings:'⚙',payout:'$',marketing:'◆',down:'⌄',play:'▶'}[n]||'•')}</span>`;
const statusClass=v=>({APPROVED:'green',SUCCESS:'green',COMPLETED:'green',ACTIVE:'green',VALID:'green',SELECTED:'green',PENDING:'pink',PENDING_L1:'pink',PENDING_L2:'pink',PENDING_L3:'pink',PROCESSING:'blue',RETRYING:'blue',SUBMITTED:'navy',DRAFT:'navy',READY:'gray',NOT_STARTED:'gray',NOT_SELECTED:'gray',UPLOADED:'gray',DUPLICATE:'purple',UNKNOWN:'orange',PARTIALLY_FAILED:'orange',RECONCILIATION_REQUIRED:'orange',BLOCKED_BY_LIMIT:'orange',FAILED:'red',INVALID:'red',REJECTED:'red',BLOCKED:'red',INACTIVE:'gray'}[v]||'gray');
const pretty=v=>String(v||'—').replace('PENDING_L','Pending L').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const pill=(v,l)=>`<span class="v2-pill v2-pill-${statusClass(v)}">${esc(l||pretty(v))}</span>`;
const uid=p=>`${p}-${Math.random().toString(36).slice(2,8)}`;

function conditionText(c){
  if(!c||c.basis==='ALWAYS')return 'Always';
  if(c.operator==='BETWEEN')return `${Number(c.from||0).toLocaleString('vi-VN')} < File Total Amount ≤ ${Number(c.to||0).toLocaleString('vi-VN')} VND`;
  return `File Total Amount > ${Number(c.from||0).toLocaleString('vi-VN')} VND`;
}
function conditionMatches(c,amount){if(!c||c.basis==='ALWAYS')return true; if(c.operator==='BETWEEN')return amount>Number(c.from||0)&&amount<=Number(c.to||0); return amount>Number(c.from||0)}
function approverNames(step){
  const refs=step.approverRefs||[];
  if(step.approverType==='ROLE')return refs.join(' / ')||'No role';
  return refs.map(id=>USERS.find(u=>u.id===id)).filter(Boolean).map(u=>`${u.name} · ${u.email}`).join(' / ')||'No user';
}
function canAct(step,user){if(!step||!user)return false;const refs=step.approverRefs||[];return step.approverType==='ROLE'?user.roles.some(r=>refs.includes(r)):refs.includes(user.id)}
function resolvePolicy(policies,amount){
  const matches=policies.filter(p=>p.status==='ACTIVE'&&conditionMatches(p.condition,amount)).sort((a,b)=>b.priority-a.priority);
  if(!matches.length)return {error:'NO_MATCHING_POLICY'};
  const top=matches.filter(p=>p.priority===matches[0].priority);
  if(top.length>1)return {error:'AMBIGUOUS_POLICY'};
  return {policy:top[0]};
}
function snapshotPolicy(p,amount){return {policyId:p.id,policyName:p.name,policyVersion:p.version,matchedCondition:conditionText(p.condition),approvalTotalAmount:amount,steps:p.steps.map((s,i)=>({...clone(s),label:approverNames(s),status:i===0?'PENDING':'NOT_STARTED',actedBy:'',actedAt:'',remark:''}))}}
function currentStep(r){return r.approvalSnapshot?.steps?.find(s=>s.status==='PENDING')}
function log(r,action,detail,actor='SYSTEM'){r.activity||=[];r.activity.push({at:now(),actor,action,detail})}

const INITIAL_POLICIES=[
  {id:'POL-GLOBAL-001',name:'Low value payout',priority:100,status:'ACTIVE',version:1,condition:{basis:'FILE_TOTAL_AMOUNT',operator:'BETWEEN',from:0,to:5000000},steps:[{order:1,level:'L1',approverType:'ROLE',approverRefs:['Growth Head']}]},
  {id:'POL-GLOBAL-002',name:'Medium value payout',priority:100,status:'ACTIVE',version:2,condition:{basis:'FILE_TOTAL_AMOUNT',operator:'BETWEEN',from:5000000,to:10000000},steps:[{order:1,level:'L1',approverType:'ROLE',approverRefs:['Growth Head','Ops Approver']},{order:2,level:'L2',approverType:'USER',approverRefs:['u-finance-manager','u-finance-ops']}]},
  {id:'POL-GLOBAL-003',name:'High value payout',priority:100,status:'ACTIVE',version:1,condition:{basis:'FILE_TOTAL_AMOUNT',operator:'GREATER_THAN',from:10000000,to:null},steps:[{order:1,level:'L1',approverType:'ROLE',approverRefs:['Growth Head','Ops Approver']},{order:2,level:'L2',approverType:'ROLE',approverRefs:['Finance Approver','Finance Manager']},{order:3,level:'L3',approverType:'USER',approverRefs:['u-director']}]},
  {id:'POL-GLOBAL-DEFAULT',name:'Default approval route',priority:10,status:'ACTIVE',version:1,condition:{basis:'ALWAYS',operator:'ALWAYS',from:null,to:null},steps:[{order:1,level:'L1',approverType:'ROLE',approverRefs:['Growth Head']}]},
];

function makeAcceptedRows(count=60,prefix='TDREF-DEMO'){return Array.from({length:count},(_,i)=>({id:`REC-${prefix}-${i+1}`,rowNumber:i+1,sourceRecordId:`${prefix}-${String(i+1).padStart(4,'0')}`,customerId:`C${String(7000+i+1).padStart(6,'0')}`,campaignId:'TD_REFERRAL_2026',expectedAmount:100000,accountRef:`0012${String(i+1).padStart(8,'0')}`,eligibilityDate:'2026-08-06',selected:true,payoutStatus:'READY',actualAmount:null,liabTransactionId:'',errorCode:'',errorMessage:'',retryCount:0}))}
function seededRequests(){
  const rows=makeAcceptedRows(60,'TDREF-20260807');
  return [
    {id:'PAY-20260807-002',filename:'td_referral_demo_67_rows.xlsx',description:'TD Referral payout demo',campaignId:'TD_REFERRAL_2026',campaignName:'TD Referral 2026',maker:'growth.mkt@cake.vn',uploadedAt:'2026-08-07T14:05:20',submittedAt:'2026-08-07T14:10:00',checksum:'demo-y3wp58f6',importedRows:67,acceptedRows:60,rejectedRows:7,records:rows,approvalTotalAmount:6000000,approvalStatus:'PENDING_L2',processingStatus:'NOT_STARTED',sentToLiabCount:0,
      approvalSnapshot:{policyId:'POL-GLOBAL-002',policyName:'Medium value payout',policyVersion:2,matchedCondition:'5.000.000 < File Total Amount ≤ 10.000.000 VND',approvalTotalAmount:6000000,steps:[{order:1,level:'L1',approverType:'ROLE',approverRefs:['Growth Head','Ops Approver'],label:'Growth Head / Ops Approver',status:'APPROVED',actedBy:'growth.head@cake.vn',actedAt:'2026-08-07T14:15:00',remark:''},{order:2,level:'L2',approverType:'USER',approverRefs:['u-finance-manager','u-finance-ops'],label:'Finance Manager · finance.manager@cake.vn / Finance Ops · finance.ops@cake.vn',status:'PENDING',actedBy:'',actedAt:'',remark:''}]},
      activity:[{at:'2026-08-07T14:05:20',actor:'growth.mkt@cake.vn',action:'UPLOAD_VALIDATION',detail:'Imported 67 rows · accepted 60 · rejected 7'},{at:'2026-08-07T14:10:00',actor:'growth.mkt@cake.vn',action:'SUBMIT_APPROVAL',detail:'Only 60 accepted records were saved to the payout request.'},{at:'2026-08-07T14:15:00',actor:'growth.head@cake.vn',action:'APPROVE_L1',detail:'Waiting for L2 user approver'}]},
  ];
}

const S={page:'requests',requests:seededRequests(),policies:clone(INITIAL_POLICIES),id:null,tab:'overview',recordTab:'success',modal:null,payload:null,menu:null,upload:null,uploadTab:'valid',policy:null,actorId:'u-finance-manager'};
const root=document.querySelector('#app');

function sidebar(){return `<aside class="v2-sidebar"><div class="v2-brand"><div class="v2-brand-mark">C</div><div><strong>Cake Portal</strong><small>version: payout-prototype-mvp</small></div></div><div class="v2-pinned"><span>PINNED</span><span>0/3</span></div><div class="v2-pin-hint">Hover a menu item and pin it here</div><div class="v2-section-title">${icon('marketing')}<span>Marketing & Campaigns</span>${icon('down')}</div><nav>${['Trigger Campaign','Affiliate Campaign','Audience','Push','Voucher'].map(x=>`<div class="v2-passive-nav">${x}</div>`).join('')}<div class="v2-nav-group"><div class="v2-nav-parent">${icon('payout')}<span>Payout</span>${icon('down')}</div><button data-nav="requests" class="v2-nav-child ${['requests','detail'].includes(S.page)?'active':''}">Payout Requests</button></div><button data-nav="config" class="v2-top-nav ${S.page==='config'?'active':''}">${icon('settings')}<span>Approval Configuration</span></button><div class="v2-passive-nav">Offering</div></nav></aside>`}
function render(){root.innerHTML=`<div class="v2-shell">${sidebar()}<main class="v2-main"><div class="v2-topbar"></div><div class="v2-content">${S.page==='requests'?requestsPage():S.page==='detail'?detailPage():configPage()}</div></main>${modal()}</div>`;bind()}

function approvalControl(r){const step=currentStep(r);if(!step)return pill(r.approvalStatus);return `<div class="v2-approval-menu-wrap"><button data-toggle="${r.id}" class="v2-approval-status-btn"><span>${pretty(r.approvalStatus)}</span>${icon('down')}</button>${S.menu===r.id?`<div class="v2-approval-menu"><button data-row-approve="${r.id}" class="v2-approval-menu-item"><span>→</span>${pill('APPROVED','Approve')}<small>${step.level} · ${esc(step.label)}</small></button><button data-row-reject="${r.id}" class="v2-approval-menu-item danger"><span>→</span>${pill('REJECTED','Reject')}<small>Remark required</small></button></div>`:''}</div>`}
function requestsPage(){return `<div class="v2-page-stack"><section class="v2-filter-card"><input placeholder="Campaign ID / Name"><select><option>Approval Status</option><option>Pending L1</option><option>Pending L2</option><option>Approved</option><option>Rejected</option></select><input placeholder="Filename"><input placeholder="Maker"><button class="v2-btn v2-primary">${icon('search')} Search</button></section><section class="v2-card"><div class="v2-toolbar"><div><h2>Payout Requests</h2><p>Upload, approve and simulate LIAB payout processing.</p></div><button data-action="upload" class="v2-btn v2-primary">${icon('upload')} Upload payout file</button></div><div class="v2-table-wrap"><table><thead><tr><th>ID</th><th>Filename</th><th>Campaign</th><th>Accepted / Imported</th><th>Total Amount</th><th>Approval</th><th>Current Approver</th><th>Maker</th><th>Uploaded Date</th><th>Processing</th><th></th></tr></thead><tbody>${S.requests.map(r=>{const step=currentStep(r);return `<tr><td>${r.id}</td><td><button class="v2-link" data-open="${r.id}">${esc(r.filename)}</button></td><td><b>${esc(r.campaignName)}</b><small>${esc(r.campaignId)}</small></td><td>${r.acceptedRows} / ${r.importedRows}</td><td>${money(r.approvalTotalAmount)}</td><td>${approvalControl(r)}</td><td>${step?`<b>${esc(step.label)}</b><small>${step.level} · ${step.approverType}</small>`:'—'}</td><td>${esc(r.maker)}</td><td>${dt(r.uploadedAt)}</td><td>${pill(r.processingStatus)}</td><td><button class="v2-icon-btn" data-open="${r.id}">${icon('eye')}</button></td></tr>`}).join('')}</tbody></table></div></section></div>`}

function liabStats(r){const success=r.records.filter(x=>x.payoutStatus==='SUCCESS').length,failed=r.records.filter(x=>x.payoutStatus==='FAILED').length,unknown=r.records.filter(x=>x.payoutStatus==='UNKNOWN').length,processing=r.records.filter(x=>['SUBMITTED','PROCESSING'].includes(x.payoutStatus)).length;return {success,failed,unknown,processing,processed:success+failed,exception:failed+unknown,sent:r.sentToLiabCount||0}}
function detailPage(){const r=S.requests.find(x=>x.id===S.id);if(!r){S.page='requests';return requestsPage()}const st=liabStats(r);return `<div class="v2-page-stack"><section class="v2-card"><button data-nav="requests" class="v2-back">${icon('back')} Back to Payout Requests</button><div class="v2-detail-title"><div><span class="v2-eyebrow">PAYOUT REQUEST</span><h1>${r.id}</h1><p>${esc(r.filename)} · ${esc(r.campaignName)}</p></div><div class="v2-detail-actions"><div>${pill(r.approvalStatus)} ${pill(r.processingStatus)}</div>${processingButton(r)}</div></div><div class="v2-summary-grid"><div><span>Imported Rows</span><strong>${r.importedRows}</strong></div><div><span>Accepted for Payout</span><strong>${r.acceptedRows}</strong></div><div><span>Sent to LIAB</span><strong>${st.sent}</strong></div><div><span>Processed by LIAB</span><strong>${st.processed}</strong></div></div></section><section class="v2-card v2-detail-card"><div class="v2-tabs">${[['overview','Overview'],['records','Records'],['approval','Approval'],['activity','Activity Log']].map(([k,l])=>`<button data-tab="${k}" class="${S.tab===k?'active':''}">${l}</button>`).join('')}</div>${S.tab==='overview'?overview(r,st):S.tab==='records'?recordsTab(r,st):S.tab==='approval'?approvalTab(r):activityTab(r)}</section></div>`}
function processingButton(r){if(r.approvalStatus!=='APPROVED')return'';if(r.processingStatus==='SUBMITTED')return `<button data-action="liab-processing" class="v2-btn v2-secondary">${icon('play')} Simulate LIAB → PROCESSING</button>`;if(r.processingStatus==='PROCESSING')return `<button data-action="liab-final" class="v2-btn v2-primary">${icon('refresh')} Simulate LIAB final result</button>`;return''}
function overview(r,st){return `<div class="v2-detail-body"><div class="v2-metric-grid">${[['Imported rows',r.importedRows],['Accepted for payout',r.acceptedRows],['Sent to LIAB',st.sent],['Processed by LIAB',st.processed],['Payout success',st.success],['Payout failed',st.failed],['Unknown / reconcile',st.unknown],['Still processing',st.processing]].map(([l,v])=>`<div><span>${l}</span><strong>${v}</strong></div>`).join('')}</div><div class="v2-two-col"><div class="v2-panel"><h3>Payout source</h3><dl><dt>Description</dt><dd>${esc(r.description)}</dd><dt>Imported</dt><dd>${r.importedRows} rows</dd><dt>Accepted</dt><dd>${r.acceptedRows} rows</dd><dt>Rejected at import</dt><dd>${r.rejectedRows} rows (summary only; rejected rows are not stored in this request)</dd></dl></div><div class="v2-panel"><h3>Approval snapshot</h3><dl><dt>Policy</dt><dd>${esc(r.approvalSnapshot?.policyName||'—')}</dd><dt>Version</dt><dd>v${r.approvalSnapshot?.policyVersion||'—'}</dd><dt>Condition</dt><dd>${esc(r.approvalSnapshot?.matchedCondition||'—')}</dd><dt>Current approver</dt><dd>${esc(currentStep(r)?.label||'—')}</dd></dl></div></div>${r.approvalStatus==='APPROVED'&&r.processingStatus==='SUBMITTED'?`<div class="v2-warning-strip">${icon('warning')}<div><strong>Final approval completed — LIAB call triggered.</strong><span>The request now contains only the ${r.acceptedRows} accepted payout records.</span></div></div>`:''}</div>`}
function recordsTab(r,st){const success=r.records.filter(x=>x.payoutStatus==='SUCCESS'),exceptions=r.records.filter(x=>['FAILED','UNKNOWN'].includes(x.payoutStatus));const rows=S.recordTab==='success'?success:exceptions;return `<div class="v2-detail-body"><div class="v2-toolbar"><div><h3>LIAB payout results</h3><p>Only records with LIAB payout outcomes are shown here. Import-validation failures are not stored in the request.</p></div><button data-action="export" class="v2-btn v2-secondary">${icon('download')} Export result</button></div><div class="v2-subtabs"><button data-record-tab="success" class="${S.recordTab==='success'?'active':''}">Payout Success <span>${success.length}</span></button><button data-record-tab="failed" class="${S.recordTab==='failed'?'active':''}">Failed / Exception <span>${exceptions.length}</span></button></div>${rows.length?resultTable(rows):`<div class="v3-empty-result">${r.processingStatus==='PROCESSING'?'LIAB is still processing these records.':'No LIAB result in this category yet.'}</div>`}</div>`}
function resultTable(rows){return `<div class="v2-table-wrap v2-record-table"><table><thead><tr><th>Source Record ID</th><th>Customer</th><th>Expected</th><th>Actual</th><th>Payout Status</th><th>LIAB Txn</th><th>Error Detail</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.sourceRecordId)}</td><td>${esc(x.customerId)}</td><td>${money(x.expectedAmount)}</td><td>${x.actualAmount==null?'—':money(x.actualAmount)}</td><td>${pill(x.payoutStatus)}</td><td>${esc(x.liabTransactionId||'—')}</td><td class="v2-error-cell">${esc(x.errorMessage||x.errorCode||'—')}</td><td>${x.payoutStatus==='FAILED'?`<button data-retry="${x.id}" class="v2-link">${icon('retry')} Retry</button>`:x.payoutStatus==='UNKNOWN'?`<button data-reconcile="${x.id}" class="v2-link">${icon('refresh')} Reconcile</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}
function approvalTab(r){const step=currentStep(r);return `<div class="v2-detail-body v2-approval-layout"><div><h3>Approval route</h3><p>ROLE means any user having one of the configured roles can approve. USER means only one of the configured usernames can approve.</p><div class="v2-timeline">${(r.approvalSnapshot?.steps||[]).map(s=>`<div class="v2-step"><div class="v2-step-dot ${s.status.toLowerCase()}">${s.status==='APPROVED'?'✓':s.order}</div><div><b>${s.level} · ${esc(s.label)}</b><p>${pill(s.status)} ${s.actedBy?`by ${esc(s.actedBy)} · ${dt(s.actedAt)}`:''}</p><small>${s.approverType} · ${s.approverRefs.length} target(s)</small></div></div>`).join('')}</div></div><aside class="v2-panel"><h3>${esc(r.approvalSnapshot?.policyName||'Approval policy')}</h3><p><b>Version:</b> v${r.approvalSnapshot?.policyVersion||'—'}</p><p><b>Condition:</b> ${esc(r.approvalSnapshot?.matchedCondition||'—')}</p><p><b>Approval total:</b> ${money(r.approvalTotalAmount)}</p>${step?`<hr><span>Current step</span><h3>${step.level} · ${esc(step.label)}</h3><div class="v2-actions"><button data-action="approve" class="v2-btn v2-success">${icon('check')} Approve</button><button data-action="reject" class="v2-btn v2-danger-outline">${icon('x')} Reject</button></div>`:r.approvalStatus==='APPROVED'?`<div class="v2-success-box">${icon('check')} Final approved. LIAB auto-call has been triggered.</div>`:''}</aside></div>`}
function activityTab(r){return `<div class="v2-detail-body"><div class="v2-activity">${(r.activity||[]).slice().reverse().map(a=>`<div><time>${dt(a.at)}</time><b>${esc(a.action.replaceAll('_',' '))}</b><span>${esc(a.actor)}</span><p>${esc(a.detail)}</p></div>`).join('')}</div></div>`}

function configPage(){return `<div class="v2-page-stack"><section class="v2-filter-card"><input placeholder="Rule name"><select><option>Status</option><option>ACTIVE</option><option>DRAFT</option><option>INACTIVE</option></select><button class="v2-btn v2-primary">${icon('search')} Search</button></section><section class="v2-card"><div class="v2-toolbar"><div><h2>Approval Configuration</h2><p>Global approval rules. Each step supports multiple ROLE targets or multiple USER targets.</p></div><button data-action="new-policy" class="v2-btn v2-primary">${icon('plus')} Create approval rule</button></div><div class="v2-table-wrap"><table><thead><tr><th>Policy</th><th>Condition</th><th>Approval Route</th><th>Priority</th><th>Version</th><th>Status</th><th></th></tr></thead><tbody>${S.policies.map(p=>`<tr><td><b>${esc(p.name)}</b><small>${p.id}</small></td><td><span class="v2-condition">${esc(conditionText(p.condition))}</span></td><td>${p.steps.map(s=>`<div><b>${s.level}</b> · ${s.approverType}: ${esc(approverNames(s))}</div>`).join('')}</td><td>${p.priority}</td><td>v${p.version}</td><td>${pill(p.status)}</td><td><button data-edit-policy="${p.id}" class="v2-icon-btn">${icon('pencil')}</button></td></tr>`).join('')}</tbody></table></div></section></div>`}

function buildDemoRows(){
  const rows=Array.from({length:67},(_,i)=>({rowNumber:i+1,sourceRecordId:`TDREF-DEMO-${String(i+1).padStart(4,'0')}`,customerId:`C${String(7000+i+1).padStart(6,'0')}`,campaignId:'TD_REFERRAL_2026',expectedAmount:100000,accountRef:`0012${String(i+1).padStart(8,'0')}`,eligibilityDate:'2026-08-06',validationStatus:'VALID',errors:[]}));
  rows[60].sourceRecordId=rows[4].sourceRecordId;rows[60].validationStatus='DUPLICATE';rows[60].errors=['Duplicate source_record_id in source file'];
  rows[61].sourceRecordId=rows[11].sourceRecordId;rows[61].validationStatus='DUPLICATE';rows[61].errors=['Duplicate source_record_id in source file'];
  rows[62].sourceRecordId=rows[17].sourceRecordId;rows[62].validationStatus='DUPLICATE';rows[62].errors=['Duplicate source_record_id in source file'];
  rows[63].customerId='';rows[63].validationStatus='INVALID';rows[63].errors=['Missing customer_id'];
  rows[64].expectedAmount=120000;rows[64].validationStatus='INVALID';rows[64].errors=['Amount mismatch: configured reward is 100,000 VND'];
  rows[65].accountRef='';rows[65].validationStatus='INVALID';rows[65].errors=['Missing account_ref'];
  rows[66].eligibilityDate='';rows[66].validationStatus='INVALID';rows[66].errors=['Missing eligibility_date'];
  return rows;
}
function analyzeUpload(rows,campaignId){const valid=rows.filter(r=>r.validationStatus==='VALID'),failed=rows.filter(r=>r.validationStatus!=='VALID'),amount=valid.reduce((s,r)=>s+r.expectedAmount,0),resolution=resolvePolicy(S.policies,amount);return {rows,valid,failed,amount,resolution,campaignId}}
function uploadModal(){const u=S.upload||{campaignId:'TD_REFERRAL_2026',description:'TD Referral payout demo',filename:'td_referral_demo_67_rows.xlsx',analysis:null};S.upload=u;const a=u.analysis;return `<div class="v2-overlay"><div class="v2-modal v2-modal-wide"><div class="v2-modal-head"><h2>Upload payout file</h2><button data-close>×</button></div><div class="v2-form-grid"><label>Campaign<select id="up-campaign">${CAMPAIGNS.map(c=>`<option value="${c.id}" ${u.campaignId===c.id?'selected':''}>${c.name}</option>`).join('')}</select></label><label>Description<input id="up-description" value="${esc(u.description)}"></label><label class="v2-span-2">Source file<input id="up-file" type="file" accept=".csv,.xlsx,.xls"></label></div><div class="v2-actions"><button data-action="demo-file" class="v2-btn v2-secondary">Use 67-row demo file</button></div>${a?uploadReview(a):''}<div class="v2-modal-actions"><button data-close class="v2-btn v2-secondary">Cancel</button><button data-action="submit-upload" class="v2-btn v2-primary" ${!a||a.resolution.error?'disabled':''}>Submit for approval</button></div></div></div>`}
function uploadReview(a){const rows=S.uploadTab==='valid'?a.valid:a.failed;return `<div class="v2-upload-analysis"><div class="v2-metric-grid"><div><span>Imported</span><strong>${a.rows.length}</strong></div><div><span>Valid / Accepted</span><strong>${a.valid.length}</strong></div><div><span>Failed validation</span><strong>${a.failed.length}</strong></div><div><span>Approval Total</span><strong>${money(a.amount)}</strong></div></div><div class="v2-panel"><p><b>Resolved policy:</b> ${a.resolution.policy?`${esc(a.resolution.policy.name)} · v${a.resolution.policy.version}`:`${esc(a.resolution.error)}`}</p><p><b>Route:</b> ${a.resolution.policy?a.resolution.policy.steps.map(s=>`${s.level} ${s.approverType}: ${esc(approverNames(s))}`).join(' → '):'—'}</p></div><div class="v2-subtabs"><button data-upload-tab="valid" class="${S.uploadTab==='valid'?'active':''}">Valid / Ready to submit <span>${a.valid.length}</span></button><button data-upload-tab="failed" class="${S.uploadTab==='failed'?'active':''}">Failed validation <span>${a.failed.length}</span></button></div><div class="v2-table-wrap v2-upload-table"><table><thead><tr><th>Row</th><th>Source Record ID</th><th>Customer</th><th>Campaign</th><th>Expected</th><th>Account Ref</th><th>Eligible Date</th><th>Validation</th><th>Error / Reason</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.rowNumber}</td><td>${esc(r.sourceRecordId)}</td><td>${esc(r.customerId||'—')}</td><td>${r.campaignId}</td><td>${money(r.expectedAmount)}</td><td>${esc(r.accountRef||'—')}</td><td>${esc(r.eligibilityDate||'—')}</td><td>${pill(r.validationStatus)}</td><td class="v2-error-cell">${esc(r.errors.join('; ')||'—')}</td></tr>`).join('')}</tbody></table></div></div>`}

function approvalConfirm(r,action){const step=currentStep(r),actor=USERS.find(u=>u.id===S.actorId)||USERS[0],allowed=canAct(step,actor),final=action==='approve'&&r.approvalSnapshot.steps.filter(s=>s.status!=='APPROVED').length===1;return `<div class="v2-overlay"><div class="v2-modal"><div class="v2-modal-head"><h2>${action==='approve'?'Confirm approval':'Confirm rejection'}</h2><button data-close>×</button></div>${final?`<div class="v2-warning-box">${icon('warning')}<div><strong>Final approval warning</strong><p>After this approval, Payout Tool will automatically call LIAB to execute the payout. Please verify the request carefully.</p></div></div>`:''}<div class="v2-panel"><p><b>Step:</b> ${step.level}</p><p><b>Allowed by:</b> ${step.approverType} · ${esc(step.label)}</p><label>Act as<select id="actor-select">${USERS.map(u=>`<option value="${u.id}" ${u.id===actor.id?'selected':''}>${esc(u.name)} · ${esc(u.email)} · ${esc(u.roles.join(', '))}</option>`).join('')}</select></label><p class="${allowed?'v3-authorized':'v2-red'}"><b>${allowed?'Authorized':'Not authorized'}:</b> ${esc(actor.name)} ${allowed?'matches this step configuration.':'does not match the configured ROLE/USER targets.'}</p></div>${action==='reject'?`<label>Remark<textarea id="reject-remark" placeholder="Required"></textarea></label>`:''}<div class="v2-modal-actions"><button data-close class="v2-btn v2-secondary">Cancel</button><button data-action="confirm-${action}" class="v2-btn ${action==='approve'?'v2-success':'v2-danger'}" ${!allowed?'disabled':''}>${action==='approve'?'Confirm Approve':'Confirm Reject'}</button></div></div></div>`}
function genericConfirm(title,body,confirmAction,label='Confirm',danger=false){return `<div class="v2-overlay"><div class="v2-modal"><div class="v2-modal-head"><h2>${esc(title)}</h2><button data-close>×</button></div>${body}<div class="v2-modal-actions"><button data-close class="v2-btn v2-secondary">Cancel</button><button data-action="${confirmAction}" class="v2-btn ${danger?'v2-danger':'v2-primary'}">${esc(label)}</button></div></div></div>`}
function policyModal(){const p=S.policy;return `<div class="v2-overlay"><div class="v2-modal v2-modal-wide"><div class="v2-modal-head"><h2>${p.id?'Edit':'Create'} approval rule</h2><button data-close>×</button></div><div class="v2-form-grid"><label>Rule name<input id="pol-name" value="${esc(p.name)}"></label><label>Approval basis<select id="pol-basis"><option value="FILE_TOTAL_AMOUNT" ${p.condition.basis==='FILE_TOTAL_AMOUNT'?'selected':''}>File Total Amount</option><option value="ALWAYS" ${p.condition.basis==='ALWAYS'?'selected':''}>Always</option></select></label><label>Priority<input id="pol-priority" type="number" value="${p.priority}"></label>${p.condition.basis==='FILE_TOTAL_AMOUNT'?`<label>From amount<input id="pol-from" type="number" value="${p.condition.from||0}"></label><label>To amount<input id="pol-to" type="number" value="${p.condition.to||''}" placeholder="blank = greater than From"></label>`:''}</div><h3>Approval Steps</h3><p>Each step uses one target type, but can contain multiple roles or multiple usernames.</p><div class="v2-step-editor">${p.steps.map((s,i)=>stepEditor(s,i)).join('')}</div><button data-action="add-step" class="v2-btn v2-secondary">${icon('plus')} Add approval step</button><div class="v2-modal-actions"><button data-close class="v2-btn v2-secondary">Cancel</button><button data-action="save-draft" class="v2-btn v2-secondary">Save Draft</button><button data-action="save-active" class="v2-btn v2-primary">Save & Activate</button></div></div></div>`}
function stepEditor(s,i){const opts=s.approverType==='ROLE'?ROLES:USERS;return `<div class="v3-step-card"><div class="v3-step-head"><b>L${i+1}</b><select data-step-type="${i}"><option value="ROLE" ${s.approverType==='ROLE'?'selected':''}>ROLE</option><option value="USER" ${s.approverType==='USER'?'selected':''}>USER</option></select><button data-remove-step="${i}" class="v2-btn v2-danger-lite">Remove</button></div><div class="v3-target-grid">${opts.map(o=>{const val=s.approverType==='ROLE'?o:o.id,label=s.approverType==='ROLE'?o:`${o.name} · ${o.email}`,checked=(s.approverRefs||[]).includes(val);return `<label class="v3-check"><input type="checkbox" data-step-ref="${i}" value="${esc(val)}" ${checked?'checked':''}><span>${esc(label)}</span></label>`}).join('')}</div></div>`}

function modal(){if(!S.modal)return'';const r=S.requests.find(x=>x.id===S.id)||S.requests.find(x=>x.id===S.payload?.id);if(S.modal==='upload')return uploadModal();if(S.modal==='submit-confirm'){const a=S.upload.analysis;return genericConfirm('Confirm submit for approval',`<div class="v2-confirm-summary"><div><span>Imported rows</span><b>${a.rows.length}</b></div><div><span>Accepted & saved</span><b>${a.valid.length}</b></div><div><span>Rejected & not saved</span><b>${a.failed.length}</b></div></div><div class="v2-info-strip"><strong>Only valid/accepted records will be stored in the Payout Request.</strong><span>Validation-failed rows remain visible only in this pre-submit review and summary/audit counts.</span></div>`,'confirm-submit','Submit for approval');}if(S.modal==='approve')return approvalConfirm(r,'approve');if(S.modal==='reject')return approvalConfirm(r,'reject');if(S.modal==='processing')return genericConfirm('Confirm LIAB PROCESSING simulation',`<p>This will change request Processing to <b>PROCESSING</b> and all sent records to PROCESSING.</p>`,'confirm-processing','Confirm');if(S.modal==='final')return genericConfirm('Confirm LIAB final-result simulation',`<p>This demo will return a mixed result: <b>SUCCESS</b>, <b>FAILED</b> and <b>UNKNOWN</b> records so the team can review exception handling.</p>`,'confirm-final','Simulate final result');if(S.modal==='retry')return genericConfirm('Confirm retry',`<p>Retry this FAILED payout record using the same idempotency key.</p>`,'confirm-retry','Retry');if(S.modal==='reconcile')return genericConfirm('Confirm reconciliation',`<p>Query LIAB to resolve the UNKNOWN payout result before any retry.</p>`,'confirm-reconcile','Reconcile');if(S.modal==='policy')return policyModal();return''}

function submitUpload(){const a=S.upload.analysis,c=CAMPAIGNS.find(x=>x.id===a.campaignId)||CAMPAIGNS[0],accepted=a.valid.map((x,i)=>({id:uid('REC'),rowNumber:x.rowNumber,sourceRecordId:x.sourceRecordId,customerId:x.customerId,campaignId:x.campaignId,expectedAmount:x.expectedAmount,accountRef:x.accountRef,eligibilityDate:x.eligibilityDate,selected:true,payoutStatus:'READY',actualAmount:null,liabTransactionId:'',errorCode:'',errorMessage:'',retryCount:0})),p=a.resolution.policy,snap=snapshotPolicy(p,a.amount),id=`PAY-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(S.requests.length+3).padStart(3,'0')}`,t=now();const r={id,filename:S.upload.filename||'td_referral_demo_67_rows.xlsx',description:S.upload.description,campaignId:c.id,campaignName:c.name,maker:'growth.mkt@cake.vn',uploadedAt:t,submittedAt:t,checksum:uid('demo'),importedRows:a.rows.length,acceptedRows:accepted.length,rejectedRows:a.failed.length,records:accepted,approvalTotalAmount:a.amount,approvalStatus:'PENDING_L1',processingStatus:'NOT_STARTED',sentToLiabCount:0,approvalSnapshot:snap,activity:[]};log(r,'UPLOAD_VALIDATION',`Imported ${a.rows.length} rows · accepted ${accepted.length} · rejected ${a.failed.length}`,'growth.mkt@cake.vn');log(r,'SUBMIT_APPROVAL',`Stored only ${accepted.length} accepted payout records and resolved ${p.name} v${p.version}`,'growth.mkt@cake.vn');S.requests.unshift(r);S.id=id;S.page='detail';S.tab='overview';S.modal=null;S.upload=null;}
function doApprove(){const r=S.requests.find(x=>x.id===S.id||x.id===S.payload?.id),step=currentStep(r),actor=USERS.find(u=>u.id===S.actorId);if(!canAct(step,actor))return;step.status='APPROVED';step.actedBy=actor.email;step.actedAt=now();const next=r.approvalSnapshot.steps.find(s=>s.status==='NOT_STARTED');if(next){next.status='PENDING';r.approvalStatus=`PENDING_L${next.order}`;log(r,`APPROVE_${step.level}`,`Approved by ${actor.email}. Waiting for ${next.level}: ${next.label}`,actor.email)}else{r.approvalStatus='APPROVED';r.processingStatus='SUBMITTED';r.sentToLiabCount=r.records.length;r.records.forEach(x=>x.payoutStatus='SUBMITTED');log(r,`APPROVE_${step.level}`,`Final approval by ${actor.email}; auto-call LIAB triggered for ${r.records.length} records.`,actor.email)}S.modal=null;S.payload=null;S.menu=null;}
function doReject(){const r=S.requests.find(x=>x.id===S.id||x.id===S.payload?.id),step=currentStep(r),actor=USERS.find(u=>u.id===S.actorId),remark=document.querySelector('#reject-remark')?.value.trim();if(!canAct(step,actor)||!remark){alert('Remark is required and the acting user must be authorized.');return}step.status='REJECTED';step.actedBy=actor.email;step.actedAt=now();step.remark=remark;r.approvalStatus='REJECTED';log(r,`REJECT_${step.level}`,remark,actor.email);S.modal=null;S.payload=null;S.menu=null;}
function liabProcessing(){const r=S.requests.find(x=>x.id===S.id);r.processingStatus='PROCESSING';r.records.forEach(x=>x.payoutStatus='PROCESSING');log(r,'LIAB_PROCESSING',`LIAB returned PROCESSING for ${r.records.length} records.`);S.modal=null;}
function liabFinal(){const r=S.requests.find(x=>x.id===S.id);r.records.forEach((x,i)=>{if(i<54){x.payoutStatus='SUCCESS';x.actualAmount=x.expectedAmount;x.liabTransactionId=`LIAB-${Date.now()}-${i+1}`;x.errorCode='';x.errorMessage=''}else if(i<58){x.payoutStatus='FAILED';x.actualAmount=0;x.errorCode=i%2?'ACCOUNT_CLOSED':'LIAB_TEMPORARY_ERROR';x.errorMessage=i%2?'Destination account is closed.':'LIAB temporary service error; retryable.'}else{x.payoutStatus='UNKNOWN';x.actualAmount=null;x.errorCode='LIAB_TIMEOUT';x.errorMessage='No deterministic response from LIAB. Reconciliation is required before retry.'}});r.processingStatus='PARTIALLY_FAILED';log(r,'LIAB_FINAL_RESULT','LIAB final simulation: 54 SUCCESS · 4 FAILED · 2 UNKNOWN.');S.modal=null;S.tab='overview';}
function doRetry(){const r=S.requests.find(x=>x.id===S.id),x=r.records.find(v=>v.id===S.payload?.recordId);if(x){x.payoutStatus='SUCCESS';x.actualAmount=x.expectedAmount;x.liabTransactionId=`LIAB-RETRY-${Date.now()}`;x.errorCode='';x.errorMessage='';x.retryCount=(x.retryCount||0)+1;log(r,'RETRY_SUCCESS',`${x.sourceRecordId} retry succeeded.`)}S.modal=null;S.payload=null;}
function doReconcile(){const r=S.requests.find(x=>x.id===S.id),x=r.records.find(v=>v.id===S.payload?.recordId);if(x){const success=(x.rowNumber||0)%2===0;if(success){x.payoutStatus='SUCCESS';x.actualAmount=x.expectedAmount;x.liabTransactionId=`LIAB-REC-${Date.now()}`;x.errorCode='';x.errorMessage='Reconciliation confirmed payout SUCCESS.'}else{x.payoutStatus='FAILED';x.actualAmount=0;x.errorCode='RECONCILED_NOT_EXECUTED';x.errorMessage='Reconciliation confirmed payout was not executed; record can now be retried.'}log(r,'RECONCILIATION',`${x.sourceRecordId}: ${x.payoutStatus}`)}S.modal=null;S.payload=null;}

function savePolicy(active){const p=S.policy,name=document.querySelector('#pol-name')?.value.trim(),basis=document.querySelector('#pol-basis')?.value,priority=Number(document.querySelector('#pol-priority')?.value||0);if(!name){alert('Rule name is required.');return}p.name=name;p.priority=priority;p.status=active?'ACTIVE':'DRAFT';p.condition.basis=basis;if(basis==='ALWAYS'){p.condition={basis:'ALWAYS',operator:'ALWAYS',from:null,to:null}}else{const from=Number(document.querySelector('#pol-from')?.value||0),toRaw=document.querySelector('#pol-to')?.value;p.condition={basis:'FILE_TOTAL_AMOUNT',operator:toRaw?'BETWEEN':'GREATER_THAN',from,to:toRaw?Number(toRaw):null}}if(!p.steps.length||p.steps.some(s=>!(s.approverRefs||[]).length)){alert('Every approval step must have at least one ROLE or USER target.');return}p.steps.forEach((s,i)=>{s.order=i+1;s.level=`L${i+1}`});if(p.id){const idx=S.policies.findIndex(x=>x.id===p.id);S.policies[idx]=clone(p)}else{p.id=uid('POL-GLOBAL');p.version=1;S.policies.unshift(clone(p))}S.modal=null;S.policy=null;}

function bind(){
  document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{S.page=b.dataset.nav;S.modal=null;render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{S.id=b.dataset.open;S.page='detail';S.tab='overview';render()});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;render()});document.querySelectorAll('[data-record-tab]').forEach(b=>b.onclick=()=>{S.recordTab=b.dataset.recordTab;render()});document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{S.menu=S.menu===b.dataset.toggle?null:b.dataset.toggle;render()});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{S.modal=null;S.payload=null;render()});
  document.querySelector('[data-action="upload"]')?.addEventListener('click',()=>{S.upload={campaignId:'TD_REFERRAL_2026',description:'TD Referral payout demo',filename:'td_referral_demo_67_rows.xlsx',analysis:null};S.uploadTab='valid';S.modal='upload';render()});
  document.querySelector('[data-action="demo-file"]')?.addEventListener('click',()=>{S.upload.campaignId=document.querySelector('#up-campaign').value;S.upload.description=document.querySelector('#up-description').value;const rows=buildDemoRows();S.upload.analysis=analyzeUpload(rows,S.upload.campaignId);render()});
  document.querySelector('#up-campaign')?.addEventListener('change',e=>{S.upload.campaignId=e.target.value});document.querySelector('#up-description')?.addEventListener('input',e=>{S.upload.description=e.target.value});document.querySelectorAll('[data-upload-tab]').forEach(b=>b.onclick=()=>{S.uploadTab=b.dataset.uploadTab;render()});
  document.querySelector('[data-action="submit-upload"]')?.addEventListener('click',()=>{S.modal='submit-confirm';render()});document.querySelector('[data-action="confirm-submit"]')?.addEventListener('click',()=>{submitUpload();render()});
  document.querySelectorAll('[data-row-approve]').forEach(b=>b.onclick=()=>{S.id=b.dataset.rowApprove;S.payload={id:b.dataset.rowApprove};S.modal='approve';render()});document.querySelectorAll('[data-row-reject]').forEach(b=>b.onclick=()=>{S.id=b.dataset.rowReject;S.payload={id:b.dataset.rowReject};S.modal='reject';render()});document.querySelector('[data-action="approve"]')?.addEventListener('click',()=>{S.modal='approve';render()});document.querySelector('[data-action="reject"]')?.addEventListener('click',()=>{S.modal='reject';render()});document.querySelector('#actor-select')?.addEventListener('change',e=>{S.actorId=e.target.value;render()});document.querySelector('[data-action="confirm-approve"]')?.addEventListener('click',()=>{doApprove();render()});document.querySelector('[data-action="confirm-reject"]')?.addEventListener('click',()=>{doReject();render()});
  document.querySelector('[data-action="liab-processing"]')?.addEventListener('click',()=>{S.modal='processing';render()});document.querySelector('[data-action="confirm-processing"]')?.addEventListener('click',()=>{liabProcessing();render()});document.querySelector('[data-action="liab-final"]')?.addEventListener('click',()=>{S.modal='final';render()});document.querySelector('[data-action="confirm-final"]')?.addEventListener('click',()=>{liabFinal();render()});
  document.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>{S.payload={recordId:b.dataset.retry};S.modal='retry';render()});document.querySelectorAll('[data-reconcile]').forEach(b=>b.onclick=()=>{S.payload={recordId:b.dataset.reconcile};S.modal='reconcile';render()});document.querySelector('[data-action="confirm-retry"]')?.addEventListener('click',()=>{doRetry();render()});document.querySelector('[data-action="confirm-reconcile"]')?.addEventListener('click',()=>{doReconcile();render()});
  document.querySelector('[data-action="new-policy"]')?.addEventListener('click',()=>{S.policy={id:null,name:'',priority:100,status:'DRAFT',version:1,condition:{basis:'FILE_TOTAL_AMOUNT',operator:'BETWEEN',from:0,to:5000000},steps:[{order:1,level:'L1',approverType:'ROLE',approverRefs:['Growth Head']}]};S.modal='policy';render()});document.querySelectorAll('[data-edit-policy]').forEach(b=>b.onclick=()=>{S.policy=clone(S.policies.find(p=>p.id===b.dataset.editPolicy));S.modal='policy';render()});document.querySelector('#pol-basis')?.addEventListener('change',e=>{S.policy.condition.basis=e.target.value;render()});document.querySelectorAll('[data-step-type]').forEach(s=>s.onchange=()=>{const i=Number(s.dataset.stepType),type=s.value;S.policy.steps[i].approverType=type;S.policy.steps[i].approverRefs=[type==='ROLE'?ROLES[0]:USERS[0].id];render()});document.querySelectorAll('[data-step-ref]').forEach(c=>c.onchange=()=>{const i=Number(c.dataset.stepRef),ref=c.value,refs=new Set(S.policy.steps[i].approverRefs||[]);c.checked?refs.add(ref):refs.delete(ref);S.policy.steps[i].approverRefs=[...refs];render()});document.querySelectorAll('[data-remove-step]').forEach(b=>b.onclick=()=>{S.policy.steps.splice(Number(b.dataset.removeStep),1);render()});document.querySelector('[data-action="add-step"]')?.addEventListener('click',()=>{S.policy.steps.push({order:S.policy.steps.length+1,level:`L${S.policy.steps.length+1}`,approverType:'ROLE',approverRefs:['Growth Head']});render()});document.querySelector('[data-action="save-draft"]')?.addEventListener('click',()=>{savePolicy(false);render()});document.querySelector('[data-action="save-active"]')?.addEventListener('click',()=>{savePolicy(true);render()});
  document.querySelector('[data-action="export"]')?.addEventListener('click',()=>{const r=S.requests.find(x=>x.id===S.id),csv=['source_record_id,customer_id,expected_amount,actual_amount,payout_status,error_code',...r.records.map(x=>[x.sourceRecordId,x.customerId,x.expectedAmount,x.actualAmount??'',x.payoutStatus,x.errorCode||''].join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${r.id}-result.csv`;a.click();URL.revokeObjectURL(a.href)});
}
render();
