import { state, esc, selectedRequest, currentStep, selectedRecords, issueRecords, statusClass, prettyStatus, pill, icon, errorText } from './state.js'
import { money, dateTime, shortMoney } from './approval.js'

export function sidebar() {
  const passive = [['Trigger Campaign','rocket',['Campaign List']],['Affiliate Campaign','users',['Affiliate Campaign']],['Audience','users',['Marketing','Collection']],['Push','send',['CAKE Campaign','Collection Campaign','Template Configuration','Cross Channel']],['Voucher','ticket',['Voucher Management']]]
  return `<aside class="sidebar"><div class="brand"><div class="brand-mark">C</div><div><strong>Cake Portal</strong><small>version: payout-prototype-mvp</small></div></div><div class="pinned"><span>PINNED</span><span>0/3</span></div><div class="pin-hint">Hover a menu item and pin it here</div><div class="sidebar-section">${icon('marketing')}<span>Marketing & Campaigns</span>${icon('down')}</div><nav>${passive.map(([label,ic,children]) => `<div class="nav-group"><div class="nav-parent">${icon(ic)}<span>${label}</span>${icon('down')}</div>${children.map(c => `<div class="nav-child passive">${c}</div>`).join('')}</div>`).join('')}<div class="nav-group"><div class="nav-parent payout-parent">${icon('payout')}<span>Payout</span>${icon('down')}</div><button data-nav="requests" class="nav-child nav-button ${['requests','detail'].includes(state.page) ? 'selected' : ''}">${icon('upload')} Payout Requests</button><button data-nav="config" class="nav-child nav-button ${state.page === 'config' ? 'selected' : ''}">${icon('settings')} Approval Configuration</button></div><div class="nav-group"><div class="nav-parent">${icon('layers')}<span>Offering</span>${icon('right')}</div></div></nav></aside>`
}

function approvalStatusControl(r) {
  const cur = currentStep(r), actionable = Boolean(cur), open = state.openApprovalMenuId === r.id
  return `<div class="approval-dropdown-wrap"><button ${actionable ? `data-toggle-approval="${r.id}"` : ''} class="approval-dropdown-button status-${statusClass(r.approvalStatus)} ${actionable ? '' : 'static'}"><span>${esc(prettyStatus(r.approvalStatus))}</span>${actionable ? icon('down') : ''}</button>${open && cur ? `<div class="approval-dropdown-menu"><button data-request-approve="${r.id}" class="approval-menu-item approve"><span>→</span>${pill('APPROVED','Approve')}<small>${cur.level} · ${esc(cur.label)}</small></button><button data-request-reject="${r.id}" class="approval-menu-item reject"><span>→</span>${pill('REJECTED','Reject')}<small>Remark required</small></button></div>` : ''}</div>`
}

export function requestsPage() {
  const f = state.filters
  const list = state.requests.filter(r => (!f.campaign || `${r.campaignId} ${r.campaignName}`.toLowerCase().includes(f.campaign.toLowerCase())) && (!f.approval || r.approvalStatus === f.approval) && (!f.filename || r.filename.toLowerCase().includes(f.filename.toLowerCase())) && (!f.maker || r.maker.toLowerCase().includes(f.maker.toLowerCase())))
  return `<div class="page-stack"><section class="filter-card"><input data-filter="campaign" placeholder="Campaign ID / Name" value="${esc(f.campaign || '')}"><select data-filter="approval"><option value="">Approval Status</option>${['PENDING_L1','PENDING_L2','PENDING_L3','APPROVED','REJECTED'].map(v => `<option value="${v}" ${f.approval === v ? 'selected' : ''}>${prettyStatus(v)}</option>`).join('')}</select><input data-filter="filename" placeholder="Filename" value="${esc(f.filename || '')}"><input data-filter="maker" placeholder="Maker" value="${esc(f.maker || '')}"><button class="btn btn-primary">${icon('search')} Search</button></section><section class="content-card"><div class="card-toolbar"><div><h2>Payout Requests</h2><p>Upload, validate, approve and simulate LIAB payout processing.</p></div><button data-action="open-upload" class="btn btn-primary">${icon('upload')} Upload payout file</button></div><div class="table-shell"><table><thead><tr><th>ID</th><th>Filename</th><th>Campaign</th><th>Selected</th><th>Total Amount</th><th>Approval</th><th>Current Approver</th><th>Maker</th><th>Uploaded Date</th><th>Processing</th><th></th></tr></thead><tbody>${list.map(r => { const cur = currentStep(r); return `<tr><td>${r.id}</td><td><button data-open-request="${r.id}" class="link-button">${esc(r.filename)}</button></td><td><div class="cell-title">${esc(r.campaignName)}</div><div class="cell-subtitle">${r.campaignId}</div></td><td>${r.selectedRecords.toLocaleString('vi-VN')} / ${r.totalRecords.toLocaleString('vi-VN')}</td><td>${money(r.approvalTotalAmount)}</td><td>${approvalStatusControl(r)}</td><td>${cur ? `<div class="cell-title">${esc(cur.label)}</div><div class="cell-subtitle">${cur.level} · ${cur.approverType}</div>` : '—'}</td><td>${esc(r.maker)}</td><td>${dateTime(r.uploadedAt)}</td><td>${pill(r.processingStatus)}</td><td><button data-open-request="${r.id}" class="icon-button">${icon('eye')}</button></td></tr>` }).join('')}</tbody></table>${list.length ? '' : '<div class="empty-state">No payout request found.</div>'}</div></section></div>`
}

export function detailPage() {
  const r = selectedRequest(); if (!r) return requestsPage()
  const tab = state.filters.detailTab || 'overview', selected = selectedRecords(r)
  const counts = {success:selected.filter(x => x.payoutStatus === 'SUCCESS').length,failed:selected.filter(x => x.payoutStatus === 'FAILED').length,unknown:selected.filter(x => x.payoutStatus === 'UNKNOWN').length,processing:selected.filter(x => ['PROCESSING','SUBMITTED'].includes(x.payoutStatus)).length,ready:selected.filter(x => x.payoutStatus === 'READY').length}
  return `<div class="page-stack"><section class="detail-header-card"><button data-nav="requests" class="back-button">${icon('back')} Back to Payout Requests</button><div class="detail-title-row"><div><div class="eyebrow">PAYOUT REQUEST</div><h1>${r.id}</h1><p>${esc(r.filename)} · ${esc(r.campaignName)}</p></div><div class="detail-header-actions"><div class="header-statuses">${pill(r.approvalStatus)}${pill(r.processingStatus)}</div>${processingActions(r)}</div></div><div class="summary-grid"><div><span>Approval Total</span><strong>${money(r.approvalTotalAmount)}</strong></div><div><span>Selected Records</span><strong>${r.selectedRecords.toLocaleString('vi-VN')} / ${r.totalRecords.toLocaleString('vi-VN')}</strong></div><div><span>Maker</span><strong>${esc(r.maker)}</strong></div><div><span>Uploaded At</span><strong>${dateTime(r.uploadedAt)}</strong></div></div></section><section class="content-card no-padding-top"><div class="tabs">${[['overview','Overview'],['records','Records'],['approval','Approval'],['activity','Activity Log']].map(([k,l]) => `<button data-tab="${k}" class="${tab === k ? 'active' : ''}">${l}</button>`).join('')}</div>${tab === 'overview' ? overview(r, counts) : tab === 'records' ? recordsTab(r) : tab === 'approval' ? approvalTab(r) : activityTab(r)}</section></div>`
}

function processingActions(r) {
  if (r.approvalStatus !== 'APPROVED') return ''
  if (['NOT_STARTED','SUBMITTED'].includes(r.processingStatus)) return `<button data-action="open-processing-confirm" class="btn btn-secondary btn-sm">${icon('play')} Simulate LIAB → PROCESSING</button>`
  if (r.processingStatus === 'PROCESSING') return `<button data-action="open-final-result-confirm" class="btn btn-primary btn-sm">${icon('refresh')} Simulate LIAB final result</button>`
  return ''
}

function overview(r, c) {
  return `<div class="detail-section"><div class="metric-grid">${[['Total records',r.totalRecords,''],['Selected',r.selectedRecords,'success'],['Duplicate',r.duplicateRecords,'purple'],['Invalid',r.invalidRecords,'danger'],['Processing',c.processing,''],['Success',c.success,'success'],['Failed',c.failed,'danger'],['Unknown',c.unknown,'warning']].map(([l,v,cl]) => `<div class="metric ${cl}"><span>${l}</span><strong>${v}</strong></div>`).join('')}</div><div class="info-grid two-col"><div class="info-panel"><h3>File information</h3><dl><dt>Description</dt><dd>${esc(r.description)}</dd><dt>Checksum</dt><dd>${r.checksum}</dd><dt>Submitted At</dt><dd>${dateTime(r.submittedAt)}</dd><dt>Source snapshot</dt><dd>Immutable demo snapshot</dd></dl></div><div class="info-panel"><h3>Approval snapshot</h3><dl><dt>Policy</dt><dd>${esc(r.approvalSnapshot?.policyName || '—')}</dd><dt>Version</dt><dd>v${r.approvalSnapshot?.policyVersion || '—'}</dd><dt>Condition</dt><dd>${esc(r.approvalSnapshot?.matchedCondition || '—')}</dd><dt>Current approver</dt><dd>${esc(currentStep(r)?.label || '—')}</dd></dl></div></div>${r.approvalStatus === 'APPROVED' && ['SUBMITTED','NOT_STARTED'].includes(r.processingStatus) ? `<div class="demo-callout">${icon('warning')}<div><strong>LIAB call has been triggered (demo).</strong><span>Use the simulation button above to move Processing to PROCESSING, then simulate final per-record results.</span></div></div>` : ''}</div>`
}

function recordsTab(r) {
  const sub = state.filters.recordSubTab || 'selected', selected = selectedRecords(r), issues = issueRecords(r), rows = sub === 'selected' ? selected : issues
  return `<div class="detail-section"><div class="section-toolbar"><div><h3>Payout records</h3><p>Source-file validation and LIAB payout status are kept separately per record.</p></div><button data-action="export-result" class="btn btn-secondary">${icon('download')} Export result</button></div><div class="subtabs"><button data-record-subtab="selected" class="${sub === 'selected' ? 'active' : ''}">Selected / Payout <span>${selected.length}</span></button><button data-record-subtab="issues" class="${sub === 'issues' ? 'active' : ''}">Not selected / Issues <span>${issues.length}</span></button></div>${sub === 'selected' ? selectedRecordTable(rows) : issueRecordTable(rows)}</div>`
}

function selectedRecordTable(rows) {
  return `<div class="table-shell record-table"><table><thead><tr><th>Row</th><th>Source Record ID</th><th>Customer</th><th>Campaign</th><th>Eligible Date</th><th>Expected</th><th>Actual</th><th>Payout Status</th><th>LIAB Transaction</th><th>Error Detail</th><th>Action</th></tr></thead><tbody>${rows.map(x => `<tr class="row-${statusClass(x.payoutStatus)}"><td>${x.rowNumber || '—'}</td><td>${esc(x.sourceRecordId)}</td><td>${esc(x.customerId)}</td><td>${esc(x.campaignId || '—')}</td><td>${esc(x.eligibilityDate || '—')}</td><td>${money(x.expectedAmount)}</td><td>${x.actualAmount == null ? '—' : money(x.actualAmount)}</td><td>${pill(x.payoutStatus)}</td><td>${esc(x.liabTransactionId || '—')}</td><td class="error-detail">${esc(x.errorMessage || x.errorCode || '—')}</td><td>${x.payoutStatus === 'FAILED' ? `<button data-retry="${x.id}" class="text-action">${icon('retry')} Retry</button>` : x.payoutStatus === 'UNKNOWN' ? `<button data-reconcile="${x.id}" class="text-action warning">${icon('refresh')} Reconcile</button>` : ''}</td></tr>`).join('')}</tbody></table>${rows.length ? '' : '<div class="empty-state">No selected payout records.</div>'}</div>`
}

function issueRecordTable(rows) {
  return `<div class="table-shell record-table"><table><thead><tr><th>Row</th><th>Source Record ID</th><th>Customer</th><th>Campaign</th><th>Eligible Date</th><th>Expected</th><th>Validation</th><th>Selection</th><th>Error / Reason</th></tr></thead><tbody>${rows.map(x => `<tr class="validation-row validation-${String(x.validationStatus || '').toLowerCase()}"><td>${x.rowNumber || '—'}</td><td>${esc(x.sourceRecordId || '—')}</td><td>${esc(x.customerId || '—')}</td><td>${esc(x.campaignId || '—')}</td><td>${esc(x.eligibilityDate || '—')}</td><td>${money(x.expectedAmount)}</td><td>${pill(x.validationStatus)}</td><td>${pill(x.selectionStatus || 'NOT_SELECTED')}</td><td class="error-detail">${esc(errorText(x))}</td></tr>`).join('')}</tbody></table>${rows.length ? '' : '<div class="empty-state">No validation issues or unselected records.</div>'}</div>`
}

function approvalTab(r) {
  const cur = currentStep(r)
  return `<div class="detail-section approval-layout"><div><div class="section-heading"><h3>Approval route</h3><p>Route is snapshotted at submit time. Each approval action needs explicit confirmation.</p></div><div class="approval-timeline">${(r.approvalSnapshot?.steps || []).map((s,i) => `<div class="timeline-step"><div class="timeline-dot ${s.status === 'APPROVED' ? 'done' : s.status === 'REJECTED' ? 'rejected' : s.status === 'PENDING' ? 'current' : ''}">${s.status === 'APPROVED' ? icon('check') : s.status === 'REJECTED' ? icon('x') : icon('clock')}</div>${i < r.approvalSnapshot.steps.length - 1 ? `<div class="timeline-line ${s.status === 'APPROVED' ? 'done' : ''}"></div>` : ''}<div class="timeline-content"><div class="timeline-title"><strong>${s.level}</strong>${pill(s.status)}</div><div class="timeline-approver">${esc(s.label)}</div><div class="timeline-meta">${s.approverType} · Step ${s.order}</div>${s.actedBy ? `<div class="timeline-acted">${esc(s.actedBy)} · ${dateTime(s.actedAt)}</div>` : ''}${s.remark ? `<div class="timeline-remark">“${esc(s.remark)}”</div>` : ''}</div></div>`).join('')}</div></div><aside class="approval-side-card"><div class="eyebrow">ROUTE RESOLUTION</div><h3>${esc(r.approvalSnapshot?.policyName || 'Not resolved')}</h3><dl><dt>Policy ID</dt><dd>${r.approvalSnapshot?.policyId || '—'}</dd><dt>Version</dt><dd>v${r.approvalSnapshot?.policyVersion || '—'}</dd><dt>Basis</dt><dd>${r.approvalSnapshot?.basis || '—'}</dd><dt>Matched</dt><dd>${esc(r.approvalSnapshot?.matchedCondition || '—')}</dd></dl>${cur ? `<div class="approval-action-box"><span>Current step</span><strong>${cur.level} · ${esc(cur.label)}</strong><div class="button-row"><button data-action="open-approve-confirm" class="btn btn-success">${icon('check')} Approve</button><button data-action="open-reject" class="btn btn-danger-outline">${icon('x')} Reject</button></div></div>` : r.approvalStatus === 'APPROVED' ? `<div class="success-box">${icon('check')}<div><strong>Final approved</strong><span>LIAB auto-triggered. Processing simulation is available in the page header.</span></div></div>` : ''}</aside></div>`
}

function activityTab(r) {
  return `<div class="detail-section"><div class="activity-list">${r.activity.slice().reverse().map(a => `<div class="activity-item"><div class="activity-dot"></div><div><div class="activity-title"><strong>${a.action.replaceAll('_',' ')}</strong><span>${dateTime(a.at)}</span></div><p>${esc(a.detail)}</p><small>${esc(a.actor)}</small></div></div>`).join('')}</div></div>`
}

export function configPage() {
  const q = state.filters.configQ || '', st = state.filters.configStatus || '', list = state.policies.filter(p => (!q || `${p.name} ${p.scopeId}`.toLowerCase().includes(q.toLowerCase())) && (!st || p.status === st))
  return `<div class="page-stack"><section class="filter-card"><input data-filter="configQ" placeholder="Policy name / Campaign" value="${esc(q)}"><select data-filter="configStatus"><option value="">Status</option>${['ACTIVE','DRAFT','INACTIVE'].map(v => `<option value="${v}" ${st === v ? 'selected' : ''}>${v}</option>`).join('')}</select><button class="btn btn-primary">${icon('search')} Search</button></section><section class="content-card"><div class="card-toolbar"><div><h2>Approval Configuration</h2><p>Flexible routing by conditions. MVP supports File Total Amount and Always.</p></div><button data-action="create-policy" class="btn btn-primary">${icon('plus')} Create approval rule</button></div><div class="warning-banner compact-warning">${icon('warning')} Demo thresholds/amounts are mock configuration values, not approved authority limits.</div><div class="concept-banner"><strong>Policy → Conditions → Steps</strong><span>Condition decides <em>when</em> a policy applies. Steps decide <em>who</em> must approve.</span></div><div class="table-shell"><table><thead><tr><th>Policy</th><th>Scope</th><th>Condition</th><th>Approval Route</th><th>Priority</th><th>Version</th><th>Effective</th><th>Status</th><th></th></tr></thead><tbody>${list.map(p => `<tr><td><div class="cell-title">${esc(p.name)}</div><div class="cell-subtitle">${p.id}</div></td><td>${p.scopeType === 'GLOBAL' ? 'Global' : p.scopeId}</td><td><div class="condition-chip">${p.condition.basis === 'ALWAYS' ? 'Always' : p.condition.operator === 'BETWEEN' ? `${shortMoney(p.condition.from)} < File Total ≤ ${shortMoney(p.condition.to)}` : `File Total > ${shortMoney(p.condition.from)}`}</div></td><td><div class="route-inline">${p.steps.map((s,i) => `<span>${i ? '<b>→</b>' : ''}<em>${s.level}</em> ${esc(s.label)}</span>`).join('')}</div></td><td>${p.priority}</td><td>v${p.version}</td><td>${p.effectiveFrom}${p.effectiveTo ? ` → ${p.effectiveTo}` : ' → ∞'}</td><td>${pill(p.status)}</td><td><div class="row-actions">${p.status === 'ACTIVE' ? `<button data-clone-policy="${p.id}" class="icon-button">${icon('copy')}</button>` : `<button data-edit-policy="${p.id}" class="icon-button">${icon('pencil')}</button>`}<button data-toggle-policy="${p.id}" class="icon-button">${icon('power')}</button></div></td></tr>`).join('')}</tbody></table></div></section></div>`
}
